//! Replays traces generated by the TypeScript veto machine and asserts this crate lands in the
//! same state every time.
//!
//! This is what makes "the TypeScript machine is the oracle" an enforced fact rather than a
//! comment. The subtle part of the state machine is the clock arithmetic — a pause freezing
//! accrual, the ceiling auto-resuming with nobody's signature, the remainder of a long advance
//! carrying over into the timelock — and that is precisely where two independent implementations
//! drift apart without either looking wrong on its own.
//!
//! The fixture is the *same file* the Solidity replayer reads, byte for byte:
//! `onchain/evm/test/fixtures/veto-traces.json` and `onchain/solana/tests/fixtures/veto-traces.json`
//! are written from one value by `packages/veto/scripts/generate-veto-traces.mjs`. If the two
//! chains ever replay different traces, they are no longer pinned to each other.
//!
//! Regenerate with `node packages/veto/scripts/generate-veto-traces.mjs` in the SDK repo. The TS
//! suite asserts the committed fixtures still match the oracle, so drift fails there too — and
//! regenerating is how you would "fix" this test by moving the target, so only do it when the
//! derivation was *meant* to change.
//!
//! No validator, no `anchor test`: this is a plain `cargo test` over pure functions, which is the
//! whole reason the state machine has no Solana dependency.

use gradual_veto::{abort, execute, pause, project, resume, start, Attempt, Config, State};
use serde::Deserialize;

/// Op codes shared with the generator and with the Solidity replayer.
const OP_PAUSE: u8 = 0;
const OP_RESUME: u8 = 1;
const OP_ABORT: u8 = 2;
const OP_ADVANCE: u8 = 3;
const OP_EXECUTE: u8 = 4;

/// An arbitrary non-zero epoch start. Deliberately not 0: a clock that begins at the Unix epoch
/// would hide a bug that treats `checkpoint_time == 0` as "unset".
const CLOCK_BASE: i64 = 1_700_000_000;

#[derive(Deserialize)]
#[serde(rename_all = "camelCase")]
struct Fixture {
    timelock_seconds: u64,
    pause_ceiling_seconds: u64,
    trace_count: usize,
    lengths: Vec<usize>,
    finals: Vec<u8>,
    ops_flat: Vec<u8>,
    args_flat: Vec<u64>,
}

fn load() -> Fixture {
    let path = concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/../../tests/fixtures/veto-traces.json"
    );
    let raw = std::fs::read_to_string(path)
        .unwrap_or_else(|e| panic!("cannot read the trace fixture at {path}: {e}"));
    serde_json::from_str(&raw).expect("trace fixture is not the shape this replayer expects")
}

fn config(fixture: &Fixture) -> Config {
    Config {
        pause_authority: [0xb1; 32],
        abort_authority: [0xb2; 32],
        resume_members: vec![[0xa1; 32], [0xa2; 32]],
        resume_threshold: 2,
        timelock_seconds: fixture.timelock_seconds,
        pause_ceiling_seconds: fixture.pause_ceiling_seconds,
    }
}

#[test]
fn fixture_is_internally_consistent() {
    let f = load();
    assert_eq!(f.lengths.len(), f.finals.len());
    assert_eq!(f.ops_flat.len(), f.args_flat.len());
    assert_eq!(f.lengths.iter().sum::<usize>(), f.ops_flat.len());
    assert_eq!(f.trace_count, f.lengths.len());
}

#[test]
fn fixture_is_large_and_varied_enough_to_be_evidence() {
    let f = load();
    assert!(f.lengths.len() > 100, "only {} traces", f.lengths.len());
    // Every reachable end state must appear, or the traces cover only a corner of the machine.
    for ordinal in [1u8, 2, 3, 4, 5] {
        assert!(
            f.finals.contains(&ordinal),
            "no trace ends in state {ordinal}",
        );
    }
}

#[test]
fn replays_every_trace_to_the_same_final_state() {
    let f = load();
    let config = config(&f);
    let mut cursor = 0usize;

    for (t, &length) in f.lengths.iter().enumerate() {
        let mut attempt = Attempt::default();
        let mut now = CLOCK_BASE;
        start(&mut attempt, now);

        for step in 0..length {
            let op = f.ops_flat[cursor];
            let arg = f.args_flat[cursor];
            cursor += 1;

            // The generator recorded only *legal* transitions, so a rejection here means this
            // implementation's rules disagree with the oracle's — which is the whole point.
            let outcome = match op {
                OP_PAUSE => pause(&config, &mut attempt, now),
                OP_RESUME => resume(&config, &mut attempt, now),
                OP_ABORT => abort(&config, &mut attempt, now),
                OP_EXECUTE => execute(&config, &mut attempt, now),
                OP_ADVANCE => {
                    now += arg as i64;
                    attempt = project(&config, attempt, now);
                    Ok(())
                }
                other => panic!("trace {t}, step {step}: unknown op {other}"),
            };
            outcome.unwrap_or_else(|e| {
                panic!(
                    "trace {t}, step {step}: op {op} is now rejected ({e:?}) but was legal when \
                     the fixture was generated"
                )
            });
        }

        assert_eq!(
            attempt.state.ordinal(),
            f.finals[t],
            "trace {t} now ends {:?} ({}), fixture says {}",
            attempt.state,
            attempt.state.ordinal(),
            f.finals[t],
        );
    }

    assert_eq!(cursor, f.ops_flat.len(), "not every op was replayed");
}

/// The ordinals the fixture's `finals` are written in. Pinned here because the fixture, the
/// Solidity enum and `bindings/index.ts` all depend on them agreeing, and nothing else would catch
/// a reordering of the enum.
#[test]
fn state_ordinals_are_pinned() {
    assert_eq!(State::None.ordinal(), 0);
    assert_eq!(State::Initiated.ordinal(), 1);
    assert_eq!(State::Paused.ordinal(), 2);
    assert_eq!(State::Executable.ordinal(), 3);
    assert_eq!(State::Executed.ordinal(), 4);
    assert_eq!(State::Aborted.ordinal(), 5);
}
