// SPDX-License-Identifier: MIT
pragma solidity ^0.8.25;

import { Test } from "forge-std/Test.sol";
import { GradualVeto } from "../src/GradualVeto.sol";
import { GradualVetoHarness } from "./GradualVetoHarness.sol";

/**
 * @dev Replays traces generated by the TypeScript veto machine and asserts this library lands in the
 *      same state every time.
 *
 *      This is what makes "the TypeScript machine is the oracle" an enforced fact rather than a
 *      comment. The subtle part of the state machine is the clock arithmetic — a pause freezing
 *      accrual, the ceiling auto-resuming with nobody's signature, the remainder of a long advance
 *      carrying over into the timelock — and that is precisely where two independent implementations
 *      drift apart without either looking wrong on its own.
 *
 *      Regenerate with `node packages/veto/scripts/generate-veto-traces.mjs`. The TS suite asserts
 *      the committed fixture still matches the oracle, so drift fails there too.
 */
contract VetoDifferentialTest is Test {
    uint256 internal constant OP_PAUSE = 0;
    uint256 internal constant OP_RESUME = 1;
    uint256 internal constant OP_ABORT = 2;
    uint256 internal constant OP_ADVANCE = 3;
    uint256 internal constant OP_EXECUTE = 4;

    uint256[] internal lengths;
    uint256[] internal finals;
    uint256[] internal opsFlat;
    uint256[] internal argsFlat;
    uint64 internal timelockSeconds;
    uint64 internal pauseCeilingSeconds;

    function setUp() public {
        string memory json = vm.readFile("./test/fixtures/veto-traces.json");
        lengths = vm.parseJsonUintArray(json, ".lengths");
        finals = vm.parseJsonUintArray(json, ".finals");
        opsFlat = vm.parseJsonUintArray(json, ".opsFlat");
        argsFlat = vm.parseJsonUintArray(json, ".argsFlat");
        timelockSeconds = uint64(vm.parseJsonUint(json, ".timelockSeconds"));
        pauseCeilingSeconds = uint64(vm.parseJsonUint(json, ".pauseCeilingSeconds"));
    }

    function _config() internal view returns (GradualVeto.Config memory config) {
        address[] memory members = new address[](2);
        members[0] = address(0xA1);
        members[1] = address(0xA2);
        config = GradualVeto.Config({
            pauseAuthority: address(0xB1),
            abortAuthority: address(0xB2),
            resumeMembers: members,
            resumeThreshold: 2,
            timelockSeconds: timelockSeconds,
            pauseCeilingSeconds: pauseCeilingSeconds
        });
    }

    function test_fixtureIsSubstantial() public view {
        // Guards against a truncated or empty fixture quietly turning the replay into a no-op.
        assertGt(lengths.length, 100, "too few traces to be evidence of anything");
        assertEq(lengths.length, finals.length);
        assertEq(opsFlat.length, argsFlat.length);

        uint256 total;
        for (uint256 i = 0; i < lengths.length; i++) {
            total += lengths[i];
        }
        assertEq(total, opsFlat.length, "flattened ops do not match the per-trace lengths");
    }

    /// @dev Every generated final state must be represented, or the traces are only exercising a
    ///      corner of the machine while appearing to cover it.
    function test_fixtureReachesEveryState() public view {
        bool[6] memory seen;
        for (uint256 i = 0; i < finals.length; i++) {
            seen[finals[i]] = true;
        }
        assertTrue(seen[uint256(GradualVeto.State.INITIATED)], "no trace ends INITIATED");
        assertTrue(seen[uint256(GradualVeto.State.PAUSED)], "no trace ends PAUSED");
        assertTrue(seen[uint256(GradualVeto.State.EXECUTABLE)], "no trace ends EXECUTABLE");
        assertTrue(seen[uint256(GradualVeto.State.EXECUTED)], "no trace ends EXECUTED");
        assertTrue(seen[uint256(GradualVeto.State.ABORTED)], "no trace ends ABORTED");
    }

    function test_solidityAgreesWithTheTypeScriptOracle() public {
        uint256 cursor;
        for (uint256 t = 0; t < lengths.length; t++) {
            GradualVetoHarness veto = new GradualVetoHarness(_config());
            vm.warp(1_000_000);
            veto.start();

            for (uint256 i = 0; i < lengths[t]; i++) {
                uint256 op = opsFlat[cursor];
                uint256 arg = argsFlat[cursor];
                cursor++;

                if (op == OP_PAUSE) veto.pause();
                else if (op == OP_RESUME) veto.resume();
                else if (op == OP_ABORT) veto.abort();
                else if (op == OP_EXECUTE) veto.execute();
                else if (op == OP_ADVANCE) vm.warp(block.timestamp + arg);
                else revert("unknown op in fixture");
            }

            assertEq(
                uint256(veto.state()),
                finals[t],
                string.concat("divergence from the oracle on trace ", vm.toString(t))
            );
        }
    }
}
